name: CR

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, labeled]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  release:
    if: github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'cr-tracked')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node version to 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile --prefer-offline
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

      - name: Build
        run: pnpm build
        env:
          NO_VITE_TEST_WATCHER_DEBUG: '1'

      - name: Publish to StackBlitz
        run: API_URL=https://pkg.pr.new/ pnpx pkg-pr-new@https://3d421c7f.stackblitz-cr.pages.dev/stackblitz-labs/pkg.pr.new/pkg-pr-new@256 publish --compact --no-template --pnpm './packages/*'
